<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EquipmentBorrowingManagementSystem.Api</RootNamespace>
    <AssemblyName>EquipmentBorrowingManagementSystem.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentBorrowingManagementSystem.Application\EquipmentBorrowingManagementSystem.Application.csproj" />
    <ProjectReference Include="..\EquipmentBorrowingManagementSystem.Infrastructure\EquipmentBorrowingManagementSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
